### ISSUE TITLE
Bug with getting player nicknames on Hurtworld server

### ISSUE THREAD

**Issue by SilentHillft** [xPaw/PHP-Source-Query#101]
I'm getting empty string instand of player nickname while getting player list on Hurtworld server by Query port.

`try {
	$query->Connect($server['ip'], $server['port'], 3, SourceQuery::SOURCE);
	$info = $query->GetInfo();
	$players = $query->GetPlayers();
	$rules = $query->GetRules();
} catch (Exception $e) {
	$error = $e;
} finally {
	$query->Disconnect();
}`

`echo '<li class="list-group-item">'.(empty($player['Name']) ? '-' : $player['Name']).' <span style="float: right;" class="label label-info">'.$player['TimeF'].'</span></li>';`

Sorry for my English!
Regards

**Comment by xPaw** [comment]
Hurtworld's fault, not the library's.
