### ISSUE TITLE
GetInfo: unread data?

### ISSUE THREAD

**Issue by de-salvatierra** [xPaw/PHP-Source-Query#106]
```
Exception 'xPaw\SourceQuery\Exception\InvalidPacketException' with message 'GetInfo: unread data? 19 bytes remaining in the buffer. Please report it to the library developer.'

in vendor/xpaw/php-source-query-class/SourceQuery/SourceQuery.php:348
```

The error only appears in the console application... And on Counter strike source game

**Comment by urichalex** [comment]
It appears if mbstring.func_overload is 2

**Comment by xPaw** [comment]
Definitely do not use mbstring overloading, it's not a good option and has been deprecated in PHP 7.2.0.

https://secure.php.net/manual/en/mbstring.overload.php
http://stackoverflow.com/a/8985225/2200891
