### ISSUE TITLE
Rust - GetPlayers and Rcon not working?

### ISSUE THREAD

**Issue by mooseh** [xPaw/PHP-Source-Query#108]
Hi There I know rust's rcon is not very good but I used to use your code about a year ago and it worked fine but now i cannot seem to get any data from my server other than GetInfo(), so im wondering is rust no longer working with PHP-Source-Query?

here's my code i've tried try and catch with no luck also

`public function view(Server $server)
    {

        $Query = new SourceQuery( );

        $Query->Connect($server->ip, 28015, 5, SourceQuery::SOURCE);
        $rcon = decrypt($server->rcon);
        $Query->SetRconPassword( $rcon );

        $server_info = $Query->GetInfo( );

        if ($server->app_id == 258550){
            $players = $Query->Rcon('status');
        } else {
            $players = $Query->GetPlayers();
        }

        $rcon = decrypt($server->rcon);

        dd($players);
        return view('servers.view', compact('server_info', 'players'));
    }`

This just returns 

> InvalidPacketException in SourceRcon.php line 100:
Rcon read: Failed to read any data from socket

Thanks in advance for any help you get?

**Comment by GoRiLliAz** [comment]
Hi i have same problem with cs:go en cs 1.6

Thanks in advance for fix.

**Comment by mooseh** [comment]
GoRiLliAz if you want to collaborate on a fix we can work together to see if im receiving the same issue on my system? I know this is definitely working for CSGO as i have tested with no issues at all.

**Comment by GoRiLliAz** [comment]
mooseh I'm really confused, yesterday I had this error, but today all works normally. The only thing not working is there I am on is the View.php it returns wrong error.

**Comment by mooseh** [comment]
whats your hostname? I'll see if there is an issue from my server?
also who's your host? OVH?

**Comment by GoRiLliAz** [comment]
My hostname And if you want to see the errors https://team-shark.fr/xPaw/Examples/View.php , and yes OVH

**Comment by mooseh** [comment]
have you enabled your server to allow UDP on the game firewall for the specific port you are Querying?
whats the ip of the game server?

**Comment by mooseh** [comment]
we seem to be filling up this with irrelavent comments, join my teamspeak and I can help you further.
ts.asgaming.uk

**Comment by GoRiLliAz** [comment]
Sorry I'm french, I use an online translator.

Yes I have server is a Game OVH, the configuration of the server is not at issue because another script works well him. I wanted this one to xPaw because it is cleaner.

GAME machines, OVh does the same firewall them configuration.

**Comment by mooseh** [comment]
I dont have a clue how but mine has just started working.... I changed nothing! the ghost in the machine again!

I will close this issue, GoRiLliAz if you wish to continue the conversation It would need to be on my teamspeak you still use private messaging on teamspeak.

Thanks
MooseH
