### ISSUE TITLE
Failed to read any data from socket

### ISSUE THREAD

**Issue by eikichi87** [xPaw/PHP-Source-Query#110]
Hi,
I'm getting for our CS:GO server this Error messages:

>xPaw\SourceQuery\Exception\InvalidPacketException at line 47
Failed to read any data from socket
#0 /var/web/asdf/PHP-Source-Query5/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 /var/web/asdf/PHP-Source-Query5/SourceQuery/SourceQuery.php(422): xPaw\SourceQuery\Socket->Read()
#2 /var/web/asdf/PHP-Source-Query5/Examples/View.php(28): xPaw\SourceQuery\SourceQuery->GetRules()
#3 {main}
 

PHP-Source-Query is the current version.
I have added CS:S, DOD:S, CS1.6 and Insurgency servers and its working, only by CS:GO it does not?

Edit: I have edited now the file "View.php" and disclosed on the line 28 the "Rules" option its now working.
You may look deeper into this :) .

**Comment by zsolt225** [comment]
neked is a mocskos kurva anyádat
NEM MEGY EZ A SZAR TE KÖCSÖG ÁLLJ xxdxdxdxdxmdxdÁRx dA KIBASZOTT SARKADRA A FASZOM KIVAN

**Comment by bbashy** [comment]
Thanks for noticing this! I also couldn't query CS:GO servers using the code from `View.php` with the `GetRules()` method there.

```
xPaw\SourceQuery\Exception\InvalidPacketException at line 47
Failed to read any data from socket
```
Comment out `$Rules   = $Query->GetRules( );` and it loads fine.

**Comment by JZwanepoel1996XD** [comment]
Same Issue here for CS:GO Server
Comment out $Rules = $Query->GetRules( ); and it loads fine.
