### ISSUE TITLE
Any idea what causes this error to occur when trying to query a server?

### ISSUE THREAD

**Issue by Twistedwheelbarrow** [xPaw/PHP-Source-Query#111]
This works on some, but not others. I'm assuming firewall potentionally, but I can't pretend to understand the error properly.

`Fatal error: Uncaught exception 'xPaw\SourceQuery\Exception\InvalidPacketException' with message 'Failed to read any data from socket' in /var/www/html/web2/SourceQuery/BaseSocket.php:47 Stack trace: #0 /var/www/html/web2/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array) #1 /var/www/html/web2/SourceQuery/SourceQuery.php(210): xPaw\SourceQuery\Socket->Read() #2 /var/www/html/web2/script.php(25): xPaw\SourceQuery\SourceQuery->GetInfo() #3 /var/www/html/web2/index.php(8): include('/var/www/html/w...') #4 {main} thrown in /var/www/html/web2/SourceQuery/BaseSocket.php on line 47`

This is using a modified version of the example code. I can attach a link if required.

**Comment by pkminer30** [comment]
I am also getting a similar error when doing a rust server:

Cannot get information from server. Unknown exceptionexception 'xPaw\SourceQuery\Exception\InvalidPacketException' with message 'Failed to read any data from socket' in /home/sfportal/public_html/portal/scripts/query/xpaw/BaseSocket.php:47 Stack trace: #0 /home/sfportal/public_html/portal/scripts/query/xpaw/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array) #1 /home/sfportal/public_html/portal/scripts/query/xpaw/SourceQuery.php(210): xPaw\SourceQuery\Socket->Read() #2 /home/sfportal/public_html/portal/scripts/query/xpaw/connector/loader.php(28): xPaw\SourceQuery\SourceQuery->GetInfo() #3 /home/sfportal/public_html/portal/scripts/query/xpaw/connector/loader.php(57): xPaw->getServersList() #4 /home/sfportal/public_html/portal/serverslist.php(18): xPaw->getServerTemplate() #5 {main}

However CSS server runs fine with the same code.

**Comment by pkminer30** [comment]
SourceQuery/SourceRcon.php line 140 should be commented to work with rust was my fix :)

**Comment by zsolt225** [comment]
kurva anyád
