### ISSUE TITLE
csgo | host_info_show 2

### ISSUE THREAD

**Issue by TR1D** [xPaw/PHP-Source-Query#112]
It does not work in сsgo, when: host_info_show "2"

**Comment by JackHammer29** [comment]
+1. I get getPlayers header mismatch

**Comment by xPaw** [comment]
Can't reproduce.

**Comment by TR1D** [comment]
I'm sorry, but what's the difficulty?

**Comment by xPaw** [comment]
You need to provide more details as to why it fails for you.

I've just had someone test it on CS:GO and it worked for them.

Try using these cvars: `host_name_store 1; host_info_show 2; host_players_show 2`

**Comment by TR1D** [comment]
1.0.0 works with host_info_show 2, but branche/master no
