### ISSUE TITLE
Rust : "Error sending rcon reply"

### ISSUE THREAD

**Issue by str1gh** [xPaw/PHP-Source-Query#113]
Hey,

When I try to send rcon command to my server, the console show me this yellow text : 
`Error sending rcon reply: System.NullReferenceException: Object reference not set to an instance of an object at Facepunch.RCon+RConClient.Reply (Int32 id, Int32 type, System.String msg) [0x00000] in <filename unknown>:0`

And this is what the page **RconExample.php** show when the request is done : 
`<pre class='xdebug-var-dump' dir='ltr'>
<small>C:\wamp64\www\Examples\RconExample.php:25:</small><small>string</small> <font color='#cc0000'>'[RCON][192.168.1.150:53177] eco.c balance str1gh'</font> <i>(length=48)</i>
</pre>`

I have commented the line 140 of **SourceRcon.php** but nothing change...

**Comment by mooseh** [comment]
str1gh is this rust you are trying? if so rust rcon no longer works with php source query as they are migrating over to websockets.
