### ISSUE TITLE
Playername left blank

### ISSUE THREAD

**Issue by kgp43** [xPaw/PHP-Source-Query#115]
Hi,

Thanks for this cheat class!
I got a small problem though.

On ARK: Survival Evolved sometimes playernames are hidden/blank.
'Players' show matching number.

Example:

`array (
  0 => 
  array (
    'Id' => 0,
    'Name' => '',
    'Frags' => 0,
    'Time' => 52862,
    'TimeF' => '14:41:02',
  ),
  1 => 
  array (
    'Id' => 0,
    'Name' => '',
    'Frags' => 0,
    'Time' => 36185,
    'TimeF' => '10:03:05',
  ),
  2 => 
  array (
    'Id' => 0,
    'Name' => '⠀',
    'Frags' => 0,
    'Time' => 16064,
    'TimeF' => '04:27:44',
  ),
  3 => 
  array (
    'Id' => 0,
    'Name' => 'Xagor',
    'Frags' => 0,
    'Time' => 1304,
    'TimeF' => '21:44',
  ),
)
array`

Only "Xagor" is visible.
'Players' => 4,

Do you know what is causing this problem? I see it on several servers.

**Comment by xPaw** [comment]
Something ARK does then. It's not a problem of this library.

**Comment by vichingo** [comment]
I there a way to show the full response so it can be analysed?

**Comment by kgp43** [comment]
Are you talking to me or xPaw?
