### ISSUE TITLE
Not working anywhere

### ISSUE THREAD

**Issue by Warchiefs** [xPaw/PHP-Source-Query#116]
I'm trying to use it with any Minecraft and ARK:SE servers. For example: mwplay.su:25565, 69.58.2.18:7771 - i'm sure, that all these servers are working on. 

So, when i use example View.php on my local host, i get it:

xPaw\SourceQuery\Exception\InvalidPacketException at line 47
Failed to read any data from socket

#0 /Users/Warchiefs/Downloads/PHP-Source-Query-master/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 /Users/Warchiefs/Downloads/PHP-Source-Query-master/SourceQuery/SourceQuery.php(210): xPaw\SourceQuery\Socket->Read()
#2 /Users/Warchiefs/Downloads/PHP-Source-Query-master/Examples/View.php(26): xPaw\SourceQuery\SourceQuery->GetInfo()
#3 {main}

**Comment by xPaw** [comment]
Minecraft doesn't use source query.
