### ISSUE TITLE
(Ark) Example.php/View.php dont show/list Players

### ISSUE THREAD

**Issue by Rubcub** [xPaw/PHP-Source-Query#118]
Ive a ARK-Server running. Everything is fine. Now i use ur PHP-Source-Query to get stats on the Website.
Ive 5 Players online right now. 5 are shown, but only 1 name.
![player_viewphp](https://cloud.githubusercontent.com/assets/28672480/26025713/c877fb74-37ed-11e7-9b0c-b0494d225d7d.jpg)

**Comment by xPaw** [comment]
That's an ark problem.
