### ISSUE TITLE
error on SourceQuery/SourceRcon.php::97

### ISSUE THREAD

**Issue by Sure666** [xPaw/PHP-Source-Query#123]
Hello.
I have 3 servers. 2 on hosting and 1 own machine with server.
As SourseBan I'm using `refork Material Admin` The problem `SourceQuery/SourceRcon.php::97` occurs with the third server. When adding an administrator through the web interface, when the impact on the players through the web interface (ban / kick, etc.). All ports for servers are open, remote access is also allowed.
When issuing administrator rights - they are issued, but through an error. With a ban / kick, a bug occurs through the web interface, and nothing is done.
In theory, this does not carry in itself anything critical, but it is very unpleasant.
What is the error and how can it be corrected? Thank you for your reply.
Screen Error - https://pp.userapi.com/c841435/v841435634/4f797/Hi73EjXW9So.jpg
Full Error - 
```Произошла фатальная ошибка PHP
Allowed memory size of 268435456 bytes exhausted (tried to allocate 1347703912 bytes)
/home/s/suremigk/horten-project.ru/public_html/bans/includes/SourceQuery/SourceRcon.php::97```

**Comment by xPaw** [comment]
That error means it's running out of memory. Either the server is sending a malformed response, or the response is too big.
