### ISSUE TITLE
Error using query

### ISSUE THREAD

**Issue by 9iky6** [xPaw/PHP-Source-Query#128]
Error 'Failed to read any data from socket'. Server counter-strike 1.6 (goldsource). On the source servers this error did not appear. What can be the reason?

http://prntscr.com/j3fxuu

http://prntscr.com/j45vpk

And without the SubStr is not working parsing using regular expression.

Maybe as a solution to the problem (Socket.php):

	$Buffer = new Buffer( );
	$readData = FRead( $this->Socket, $Length );
	$Buffer->Set( $readData );
	if($readData === '') {
		return $Buffer;
	}
	$this->ReadInternal( $Buffer, $Length, [ $this, 'Sherlock' ] );
	return $Buffer;

	// OR
	$Buffer = new Buffer( );
	$Buffer->Set( FRead( $this->Socket, $Length ) );
	if($Buffer->Remaining( ) == 0) {
		return $Buffer;
	}
	$this->ReadInternal( $Buffer, $Length, [ $this, 'Sherlock' ] );
	return $Buffer;

and this (in GoldSourceRcon.php):

`$StringBuffer .= SubStr( $Packet, 0, -2 );`

Sorry if bad understand me, this is google translite from russian.

**Comment by xPaw** [comment]
Non-Steam server?

**Comment by 9iky6** [comment]
Yes, non-steam rehlds, using reunion. I created fork and in it made komity, like the problem I have vanished.

**Comment by xPaw** [comment]
Not a problem with this library then, I intentionally did not support non-Steam servers.
