### ISSUE TITLE
SourceQuery doesnt work on webhost

### ISSUE THREAD

**Issue by Seralnl** [xPaw/PHP-Source-Query#129]
I've made a huge application where it uses SourceQuery to check if a garry's mod server is up, but it doesnt work on a webhost while it does work on localhost.

Message: Could not create socket: Invalid argument

Anyone that has the same problem?

Edit: The problem is NOT in my code, since i am using the same database on localhost as on the test server AND i just reuploaded all the files. It works on localhost but it doesnt work on the test server.

Edit 2: Maybe it has something to do with CloudFlare but i dont know.

**Comment by xPaw** [comment]
That's gonna be an issue with your server configuration or firewall. You'll have to figure that out yourself.
