### ISSUE TITLE
GetChallenge: Packet header mismatch. (0x6c) + IDE Warning (CS:GO)

### ISSUE THREAD

**Issue by Hexer10** [xPaw/PHP-Source-Query#132]
Hi, 
I've seen this error here: #80 , but no solution were given.
```GetChallenge: Packet header mismatch. (0x6c)```
This is my code:
```
            $rcon = new SourceQuery();
            $rcon->Connect("xxxxx.net", 27015);

            $rcon->SetRconPassword("xxxx");

            $players = $rcon->GetPlayers(); //Errored line
            //$reply;

           // foreach ($players as $player) {
           //     $reply = sprintf("%s\n", $player['name']);
           // }
          //sendMessage($reply);
```

I've already tryed to call "GetInfo()" before as stated in the previus issue, but it didn't worked.

Also could someone explain why my IDE(PHPStorm) is giving me this warning?

![image](https://user-images.githubusercontent.com/21113203/39938649-e92640e0-5553-11e8-8d24-e0477a3348d8.png)

Thanks!

**Comment by zjh4473** [comment]
how did you solve this issue??
