### ISSUE TITLE
Can't get CS:GO server rules

### ISSUE THREAD

**Issue by Lil-Pepe** [xPaw/PHP-Source-Query#135]
Hello,

Im' trying to get the rules of a CS:Go server, but it actually can't because I get this error : 
`Failed to read any data from socket` when I call the getRules function. I also get an error in View.php : 
```
xPaw\SourceQuery\Exception\InvalidPacketException at line 47
Failed to read any data from socket

#0 C:\wamp64\www\aa\SourceQuery\Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 C:\wamp64\www\aa\SourceQuery\SourceQuery.php(422): xPaw\SourceQuery\Socket->Read()
#2 C:\wamp64\www\aa\Examples\View.php(30): xPaw\SourceQuery\SourceQuery->GetRules()
#3 {main}
```
The getInfos() and getPlayers() are working, only that one (getRules()) is messing.
I'm running on PHP 7.0.10.

Thanks

**Comment by xPaw** [comment]
It's broken in CS:GO.

This plugin might make it work: https://forums.alliedmods.net/showthread.php?t=236521

**Comment by Lil-Pepe** [comment]
@xPaw Now i have another error : `GetRules: Packet header mismatch. (0x41)`
