### ISSUE TITLE
Does this work with Insurgency Sandstorm?

### ISSUE THREAD

**Issue by zdanman** [xPaw/PHP-Source-Query#138]
I've attempted to use this with Insurgency Sandstorm servers and it cannot even connect to the socket.

Any ideas on the compatibility of this?

**Comment by RomnDeveloper** [comment]
Insurgency 2 isn't a source engine game :|
This cannot be compatibility on this.

**Comment by xPaw** [comment]
It probably runs the query stuff on a separate port.

If the server implements Source query (Steam server list uses it), then this library will work.
