### ISSUE TITLE
COD MW3

### ISSUE THREAD

**Issue by tomhoogeveentje** [xPaw/PHP-Source-Query#139]
I know this is kindoff a long shot, since this repo hasn't been updated in ages. I wanted to use this code to controll an CODMW3 server, but I can't seem to get it to work. Should it still work?
what port do I need to use? This is kindoff the only piece of code I could find that said it could use RCON with CODMW3.

**Comment by tomhoogeveentje** [comment]
Oh and thanks btw, I have been using your code to RCON to CSGO and TF2, which works perfectly

**Comment by xPaw** [comment]
> I know this is kindoff a long shot, since this repo hasn't been updated in ages. I wanted to use this code to controll an CODMW3 server, but I can't seem to get it to work. Should it still work?

Just because it hasn't been updated, doesn't mean it broke on its own. The protocol has not changed.

**Comment by tomhoogeveentje** [comment]
I didn't mean to offend anyone, just thought you might not reply.

I have a server running, which is accessible from the internet etc ( so it's not some port problem ).
I get this error: "Can't connect to RCON server: Operation timed out"
I double checked the rcon password is correct.

This is the line of code i use to connect:
$Query->Connect('81.169.209.30', 27015, 1, SourceQuery::SOURCE);

**Comment by xPaw** [comment]
Steam is telling me there's The Forest server on that IP, and you query it on serverport+1, so 27016.
