### ISSUE TITLE
How to test if valid ip etc ?

### ISSUE THREAD

**Issue by BaguetteV1** [xPaw/PHP-Source-Query#140]
Hello, i'm looking how to check if information are valid, i tried this but doesn't work:
```
if (isset($_POST['check']) {
	require __DIR__ . '/script/phpquery/bootstrap.php';

	use xPaw\SourceQuery\SourceQuery;

	$Query = new SourceQuery( );
	
	try
	{
		$Query->Connect( '54.37.129.235', 27015, 1, SourceQuery::SOURCE );
		
	}
	catch( Exception $e )
	{
		echo $e->getMessage( );
	}
	finally
	{
		$Query->Disconnect( );
	}
}
```

Error:

Parse error: syntax error, unexpected 'use' (T_USE) in /var/www/html/gmodstore/admin.php on line 16

Do you have a solution ?
(It's strange because in a empty file i work, but not in my admin page

**Comment by xPaw** [comment]
This issue section is not for generic PHP questions.
