### ISSUE TITLE
Issue pulling a status from a Rust server, I am sure it is me

### ISSUE THREAD

**Issue by fluidsc** [xPaw/PHP-Source-Query#45]
Perhaps I am missing something here, but I have the library working correctly. I can speak through console using SourceQuery without issue using:

var_dump( $Query->Rcon( 'say hello there!' ) );

I would like to execute a status command and put the results into an array but when I do the following all I get back is 'Boolean false' from the var_dump:

var_dump( $Query->Rcon( 'status' ) );

Is there something I am missing? I am having a heck of a time finding documentation for SourceQuery, but  other than that it really seems great.

The PHP code I am using is as follows:

```
<?php 
require __DIR__ . '/classes/SourceQuery/SourceQuery.class.php';

// Start of RCON Connection
// LIVE SERVER
    define( 'SQ_SERVER_ADDR', 'SERVER_IP' );
    define( 'SQ_SERVER_PORT', SERVER_PORT );
    define( 'SQ_PASSWORD','PASSWORD' );
    define( 'SQ_TIMEOUT',     5 );
    define( 'SQ_ENGINE',      SourceQuery :: SOURCE );

$Query = new SourceQuery( );

try
    {
        $Query->Connect( SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE );

        $Query->SetRconPassword(SQ_PASSWORD);
        $rconstatus = $Query->Rcon('status');
        var_dump($rconstatus);
    }
    catch( Exception $e )
    {
        echo($e->getMessage());
    }

        $Query->Disconnect( );
// End of RCON connection
?>
```

**Comment by fluidsc** [comment]
I will add that I am connecting correctly to the server. I know I said that "say hello there!" worked without issue... it should not be failing and returning false.

**Comment by xPaw** [comment]
Probably related to #20

**Comment by fluidsc** [comment]
Yeah I saw that, but it seemed that person was getting an error. I just get nothing so I did not know if they were related.

Any way we can investigate this further? Is there any verbose output from the class that can be enabled? I only read source enough to know that I think everything is fine on my end.

**Comment by xPaw** [comment]
There's no verbose option.

I have a feeling this might be related to #43 as well. Sadly RCON protocol is piss poor, and there's no way to implement absolutely correctly.

`false` is most likely returned here: https://github.com/xPaw/PHP-Source-Query-Class/blob/master/SourceQuery/SourceRcon.class.php#L131

Try adding `var_dump($this->Buffer->Get());` before that return statement, and see if there's any data in the buffer.

**Comment by fluidsc** [comment]
Added some debug output to SourceQuery.class.php and it is connecting without issue. It is returning false I guess because the server response is empty. When I come out of Rcon() I am in the portion of the conditional code that is supposed to return the answer from the server as a string.

```		/**
		 * Sends a command to the server for execution.
		 *
		 * @param string $Command Command to execute
		 *
		 * @return string|bool Answer from server in string, false on failure
		 */
		public function Rcon( $Command )
		{
			if( !$this->Connected )
			{
				print('Not Connected.<br />');
				return false;
			}
			print('Connected and returning.<br />');
			return $this->Rcon->Command( $Command );
		}
```

That returns the following:

```Connected and returning.
bool(false)```

On another note, the Rcon command in RUST 'server.hostname' should simply return the name of the server, and it is doing the same thing. I wanted to try another command just to see what would happen. 

There is sadness inside of me. :(

**Comment by xPaw** [comment]
You should add debugs inside `SourceRcon.class.php` to get more information.

**Comment by xPaw** [comment]
@fluidsc did you solve this?

**Comment by fluidsc** [comment]
Was not ever able to resolve this. I was at the point when I last looked at it that I had the web site connecting to Rust, and attempting to pull the status from the server. There have been changes to Rust RCON since I last tried this. I am likely about to begin looking at this again in the next few days to try and get it resolved.

I believe the problem is that Rust, while claiming to use the Source RCON protocol, actually just does things differently.

I know several patches ago they made changes to RCON, and to be honest I just dropped this project and moved on. I do have need for it again now, and will be trying it again within the next day or two.

**Comment by xPaw** [comment]
> I believe the problem is that Rust, while claiming to use the Source RCON protocol, actually just does things differently.

That's most likely true, and thus I probably won't be able to add Rust support in this library.

**Comment by fluidsc** [comment]
I know (and understand) that you do not want to have to write hackish code, but you are way more versed in Source RCON than I am. Have you tried to run a local Rust server and look at what is actually being returned? I know there are other web-based apps that connect to Rust servers and I have seen mention that some of those use modified versions of your library to do so.

I am honestly hopeful that when I go back to this project, that it just works. I do know for a fact that they made changes to Rust RCON...but I really doubt those were the types of changes made. lol.

**Comment by Koshatul** [comment]
I found the issue I had connecting to an ARK server was https://github.com/xPaw/PHP-Source-Query/blob/master/SourceQuery/SourceRcon.class.php#L69

According to https://developer.valvesoftware.com/wiki/Source_RCON_Protocol it should be <Body>\0<Empty String>\0

Replacing it with this line worked for me.

    $Command = Pack( 'VV', ++$this->RconRequestId, $Header ) . $String . chr(0) . chr(0);

**Comment by xPaw** [comment]
Odd. Have you tried removing one extra \x00 there?

**Comment by xPaw** [comment]
@fluidsc Wanna test 60b77988634cbf96117b6e2e0b73b4a5a4e7beda?

**Comment by fluidsc** [comment]
Just got back on this little project today. Tested what you asked, and I get the same results. Now, if you look at the code I posted originally in this thread, am I just doing it wrong or what?

I am indeed connecting to the server, it is indeed committing a "status" command, but am I missing something on getting the info back from it? The pertinent code is here:

```
try
	{
		$Query->Connect( SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE );
		
		$Query->SetRconPassword(SQ_PASSWORD);
		
		$rconstatus = $Query->Rcon('status');
		var_dump($rconstatus);
	}
	catch( Exception $e )
	{
		echo('CATCH!: ' . $e->getMessage());
	}
	
		$Query->Disconnect( );
```

That part just seems to be failing somewhere. Does Rcon('status') not return anything? Is it supposed to return what is echoed to the server console? I swear maybe I am just not doing this right :D

**Comment by mooseh** [comment]
I've added this sourcequery to a project that im working on to manage our rust server also, 
I need to find a way to get the players with their SteamID's and this will enable me to add kick/ban buttons using those steamID's if someone is willing to join projects together Im sure we could help each other?

I just wish this could return the console then I could grab everything i need from that by running a status command.

**Comment by narasimha99** [comment]
i used PHP-Source-Query in local its working properly ,  but not working on server
https://beta.tbctactics.com/?page_id=1868
any software we need install on server 
any  ports we need to enable in beta.tbctactics.com, on wHicH port its sends request 

i am receive bellow response in local server.

Array ( [Protocol] => 17 [HostName] => TBC Tactics| FFA DM | M4/AK/Deagle Only [Map] => de_dust2 [ModDir] => csgo [ModDesc] => Counter-Strike: Global Offensive [AppID] => 730 [Players] => 0 [MaxPlayers] => 16 [Bots] => 0 [Dedicated] => d [Os] => l [Password] => [Secure] => 1 [Version] => 1.35.5.1 [ExtraDataFlags] => 161 [GamePort] => 27015 [GameTags] => empty,gameME,secure [GameID] => 730 )
Server Name : 	TBC Tactics| FFA DM | M4/AK/Deagle Only
