### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by Lachee** [xPaw/PHP-Source-Query#57]
Starbound allows unicodes in its character names, which is all fine and dandy for the russians, however it causes the rcon to error out.

here is the message:
`ON: Error executing: list: (UnicodeException) Codepoint too big in hexStringFromUtf32\n.\/starbound_server(_ZN4Star13StarExceptionC2ESs+0x75) [0xfa4b55]\n.\/starbound_server(_ZN4Star13StarExceptionC2EPKc+0x25) [0xfa4f25]\n.\/starbound_server(_ZN4Star18hexStringFromUtf32EDi+0x2f2) [0xf98b32]\n.\/starbound_server(_ZN4Star19escapeStringUnicodeERKSsRKSt8functionIFbDiEE+0xd7) [0xf98c37]\n.\/starbound_server(_ZN4Star16CommandProcessor4listEjRKNS_6StringE+0x32d) [0x9f51fd]\n.\/starbound_server(_ZN4Star16CommandProcessor13handleCommandEjRKNS_6StringES3_+0x525) [0x9fa2a5]\n.\/starbound_server(_ZN4Star16CommandProcessor12adminCommandERKNS_6StringES3_+0x32) [0x9fa4a2]\n.\/starbound_server(_ZN4Star14UniverseServer12adminCommandENS_6StringE+0x5b) [0x83829b]\n.\/starbound_server(_ZN4Star16ServerRconClient13handleCommandENS_6StringE+0xb41) [0x7dea91]\n.\/starbound_server(_ZN4Star16ServerRconClient14processRequestEv+0x4c6) [0x7df716]\n.\/starbound_server(_ZN4Star16ServerRconClient3runEv+0x18) [0x7e0228]\n.\/starbound_server(_ZN4Star10ThreadImpl9runThreadEPv+0x1a) [0xfad9ba]\n\/lib\/x86_64-linux-gnu\/libpthread.so.0(+0x8182) [0x7fa103eba182]\n\/lib\/x86_64-linux-gnu\/libc.so.6(clone+0x6d) [0x7fa1036dd00d]\u0000\u0000`

using the following to list all the players:`
//Connect to RCON
		$rcon = new SourceQuery( );
		$rcon->Connect( RCON_SERVER , RCON_PORT, RCON_TIMEOUT, SourceQuery :: SOURCE  );	
		$rcon->SetUseOldGetChallengeMethod(true);					
		$rcon->SetRconPassword( RCON_PASS );
		
		//Get player list	
		$player_list = $rcon->Rcon( 'list' );`

**Comment by Lachee** [comment]
this maybe starbounds fault. Sending this to devs too.

**Comment by Mechazawa** [comment]
Looks like starbound is sending a stacktrace. PHP has decent Unicode support. Maybe the message is sent as ASCII instead of UTF-8 and star bound wants to send back its data in the same format. The translation borks up and the server spits out a stacktrace. This should be solvable by forcing the internal encoding of the script to be utf-8. 

```php

**Comment by Mechazawa** [comment]
This is just speculation. I can't test this since I do not have access to a laptop/PC at thr moment nor do I have a starbound server.

**Comment by Lachee** [comment]
Im sorry, but where would I place the unicode enforcement? I have tied just before the rcon query on my script but it didn't seem to work.

**Comment by Mechazawa** [comment]
At the start of your script

**Comment by Lachee** [comment]
I have just noticed that my Starbound Launcher is displaying the name correctly. (My launcher uses RCON too, but another script [ The "GameQ" php script ] ). So maybe it isn't starbound :| 



I placed it on the top of my script with no luck.

**Comment by xPaw** [comment]
Your best bet would be contacting Starbound developers, since it's causing a stacktrace on the server. The script just sends RCON commands as a null terminated string, as per Valve's spec.

**Comment by xPaw** [comment]
I will close this issue since it appears to be a problem with the server.
