### ISSUE TITLE
Not working with arma 3

### ISSUE THREAD

**Issue by flow0815** [xPaw/PHP-Source-Query#58]
Set up all you mentioned including gameport + 1 but there is no connection to server. pulling information works but executing rcon commands results in connection timeout. other rcon tools have no problem. any fix for that?

**Comment by xPaw** [comment]
This question was asked multiple times, and as I don't play or have an Arma 3 server, I don't know if it's actually using Source RCON or not. If you could investigate it, that would be great.

**Comment by flow0815** [comment]
No idea how i should because i am not into the rcon protocoll. Just wanted to inform you because there is no issue open about that. Thanks

**Comment by jamchiv01** [comment]
From what i can tell, its done through Battle-eye not steam

**Comment by flow0815** [comment]
And that means? Nobody a working solution for that?

**Comment by jamchiv01** [comment]
From what i can gather, if the server uses battleye Rcon, not steams source, then the code used in this build wont work as it is specific to source and i have no idea if anyone is working on a solution for it.
