### ISSUE TITLE
What kind of 'credits' do you prefer?

### ISSUE THREAD

**Issue by Smurftastic** [xPaw/PHP-Source-Query#63]
Hey just checking with you since you made this wonderful plugin.

Is it alright if we leave:

    <p>WEBSITE NAME is running <a href="https://github.com/xPaw/PHP-Source-Query" target="_blank">PHP-Source-Query</a> by xPaw.<br>

    PHP-Source-Query is licensed under GNU LESSER GENERAL PUBLIC LICENSE Version 2.1, February 1999. <br>

    A copy of the license can be found <a href="PHP-Source-Query-master/LICENSE" target="_blank">here</a>. No changes were made to the <a href="https://github.com/xPaw/PHP-Source-Query/tree/master/SourceQuery" target="_blank">source code</a>.</p>

Or do you prefer it in another way?

Thanks for making our lives simpler.

**Comment by xPaw** [comment]
That's fine, if you want it like that.
