### ISSUE TITLE
ARK doesn't seem to be supported (anymore?)

### ISSUE THREAD

**Issue by Ataman** [xPaw/PHP-Source-Query#64]
Despite ARK: Survival Evolved being on the supported games list, functions like GetPlayers() don't work.
I suggest updating the list accordingly.

**Comment by Manu-Swag** [comment]
It's working, i tested it 5 mins ago.

**Comment by Ataman** [comment]
I'm trying to do the example with an official server (31.214.160.156:7781)
It returns a blank page.

**Comment by Manu-Swag** [comment]
Oh i tested it and it's working with this configuration.
IP: 31.214.160.156
PORT: 27015
TIMEOUT: 1
ENGINE: SourceQuery::SOURCE

Try it!

**Comment by Ataman** [comment]
No luck yet, seems my webserver refuses to connect to anything. (Connecting to fake IPs results in the same blank page, no errors or exceptions thrown).

**Comment by Ataman** [comment]
My host might be blocking something, I'll check back with my provider.
Since Manu-Swag confirmed it working I'll close the issue.
