### ISSUE TITLE
Query is not working on webhosting

### ISSUE THREAD

**Issue by MatusMak** [xPaw/PHP-Source-Query#65]
I've managed to run your query on my localhost without any issues. But after uploading my code to webhosting, every server status was suddenly offline. The only thing I've been able to debugg is that this chunk of code in SourceQuery::GetInfo():
```
$Type = $this->Buffer->GetByte( );
			
if( $Type === 0 )
{
	return false;
}
```
assigns 0 to $Type and therefore the method is returning false.

Do you know what might be the problem, or how to find out source of it? Again, this was not an issue while I was running the code in localhost.

**Comment by xPaw** [comment]
That's not a problem with the library, but the configuration of your host.
