### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by 404UserNotFound** [xPaw/PHP-Source-Query#66]
How would one go about modifying this so that it only displays specific information? I recently tried editing SourceQuery.class.php and removed all the Extra Data Flags, and commented out some other things such as Password, OS, Dedicated, etc.

What ended up happening was that the players/max players count started displaying in the 100's for some reason.

Ideally, this would be much better if there were multiple functions instead of just "public function GetInfo( )". for example:

"GetServerName", "GetMaxPlayers", "GetCurrentPlayers", "GetMapname", "GetServerIP", "GetServerPort", "GetServerIPWithPort".

Alas, I'm not experienced enough to figure out how to make this work.

**Comment by xPaw** [comment]
Don't modify the class itself. Just use the output variables you need.

**Comment by 404UserNotFound** [comment]
Yeah see, I'm not sure how to do that.

**Comment by xPaw** [comment]
`GetInfo()` returns an array, then you can echo variables from there, like `$Info[ 'Players' ]`.

**Comment by 404UserNotFound** [comment]
Wonderful! Thanks for the info :D
