### ISSUE TITLE
GetInfo: Packet header mismatch. (0x6d)

### ISSUE THREAD

**Issue by imaning** [xPaw/PHP-Source-Query#67]
PHP5.4+，nginx

why????

xPaw\SourceQuery\Exception\InvalidPacketException at line 277
GetInfo: Packet header mismatch. (0x6d)

#0 C:\WWW\PHP-Source-Query-master\View.php(24): SourceQuery->GetInfo()
#1 {main}

**Comment by imaning** [comment]
Counter-Strike 1.6 
hlds 6153

**Comment by xPaw** [comment]
dproto, that's why.
