### ISSUE TITLE
Socket read: Raw packet header mismatch. (0x0)

### ISSUE THREAD

**Issue by Izion** [xPaw/PHP-Source-Query#69]
Hi,

I seem to be getting the following error when trying to run the example script:

`Socket read: Raw packet header mismatch. (0x0)`
`Warning: unpack(): Type l: not enough input, need 4, have 0 in Buffer.class.php on line 125`

I have tried a few different servers (Ark Survival) but all seem to be coming back with the same problem, could this be something Iv missed, php extension for example?

Many Thanks,
Kyle

Settings:

`define( 'SQ_SERVER_ADDR', '195.62.53.69' );`
`define( 'SQ_SERVER_PORT', 27015 );`
`define( 'SQ_TIMEOUT',     3 );`
`define( 'SQ_ENGINE',      SourceQuery :: SOURCE );`

**Comment by xPaw** [comment]
195.62.53.69:27015 is not replying in the Steam browser either.

**Comment by Izion** [comment]
Hi xPaw, thanks for coming back to me. I have tried a number of servers (Checking them first in the Steam Browser), this must have been bad choice for the example.

The server i play on all the time: 80.84.53.10:23417
This one is up at the moment but still get the above error.

**Comment by xPaw** [comment]
Just test it yourself in Steam's server browser. That server doesn't reply either.

It's not a problem with the library, just a configuration error on yours/server hosts' end.

**Comment by Izion** [comment]
That's strange it shows live for me:
http://s9.postimg.org/m21r2xusf/server.jpg

This was taken just a few moments ago, I just did a call to the steam master server and it returns this server ip/port.

Not to worry though will keep playing and report back if I find where the problem is to help others.

Thanks again :)
