### ISSUE TITLE
namespaces & composer support

### ISSUE THREAD

**Issue by Gummibeer** [xPaw/PHP-Source-Query#70]
Hey,

it would be great if you can update the classes and add namespaces and support the PSR-4 autoloader from composer with this update.
I can/will provide a pull request if you want?

**Comment by xPaw** [comment]
Composer is already there, it just needs namespace in files it's missing. So yea, sure you can make a pull request.

**Comment by xPaw** [comment]
PSR-4 and namespaces are in master now, want to give it a try?
