### ISSUE TITLE
GetPlayer/GetInfo/GetRules

### ISSUE THREAD

**Issue by DisturbedGoW** [xPaw/PHP-Source-Query#71]
Hello there,

using your Lib I am not able to get any further Information from an Ark server. Is there an issue with the current vers. of the lib? I went ahead and tried the example, and the Connect works fine, but if I issue the in the Title mentioned functions, nothing happens, the arrays do not get filled. 

Any hints for clues? I am just trying to make a little tool for myself to check the status of some servers(not my own).

Kind regads,
Dist

**Comment by xPaw** [comment]
There's a bunch of issues closed just like yours already. The problem lies with your web servers or game servers' configuration.
