### ISSUE TITLE
Cant use rcon commands for ARK Survival Evolved.

### ISSUE THREAD

**Issue by HulioEglesias** [xPaw/PHP-Source-Query#76]
Cant use rcon commands in the ARK. 
Try:
$Query->SetRconPassword( 'AnyPassword' );
var_dump( $Query->Rcon( 'listplayers') );
but get a answer: "Rcon read: Failed to read any data from socket"
Why this isn't work?

**Comment by xPaw** [comment]
Do you have rcon enabled and used correct port?

**Comment by HulioEglesias** [comment]
yep,

**Comment by xPaw** [comment]
Then you're on your own to try and find the issue. Could be firewall, bad php config or similar issue.

**Comment by HulioEglesias** [comment]
I can connect throw program "ARKon"

**Comment by xPaw** [comment]
It might be your webhost config not allowing the connection. There's nothing I can help you with in solving this issue.
