### ISSUE TITLE
Wrong challenge format in A2S_PLAYER

### ISSUE THREAD

**Issue by theAsmodai** [xPaw/PHP-Source-Query#79]
Hello. In your script the A2S_PLAYER request has format
```
int | connectionless header
byte | request header
string | challenge number
```
but true format is
```
int | connectionless header
byte | request header
int | challenge number
```
Proof: https://developer.valvesoftware.com/wiki/Server_queries#A2S_PLAYER

**Comment by xPaw** [comment]
Did you run into any issues? It reads 4 raw bytes from the socket and writes them back without any type casting, and it works as expected.

**Comment by theAsmodai** [comment]
Sorry for inaccuracy. The problem is only in new challenge request. It sends -1 as a string, not as 4-byte int:
0xffffffff + 'U' + "4294967295"

**Comment by xPaw** [comment]
Hm yeah I can see that. But does this cause any issues in any game? I haven't run into any.

**Comment by theAsmodai** [comment]
Thanks! Yes, there may be problems with the exact protocol implementations.

**Comment by xPaw** [comment]
Sadly there is no "exact" protocol implementation. It's just a hack job that ended up being popular.
