### ISSUE TITLE
GetChallenge: Packet header mismatch. (0x6c) issue

### ISSUE THREAD

**Issue by EnvoxX** [xPaw/PHP-Source-Query#80]
Hi,

I get an issue when i'm trying to use GetInfo:
 "GetInfo: Packet header mismatch. (0x6c)"

I'm able to find my server CS:GO on my steam browser.

	// Edit this ->
	define( 'SQ_SERVER_ADDR', '5.196.58.216' );
	define( 'SQ_SERVER_PORT', 27042 );
	define( 'SQ_TIMEOUT',     3 );
	define( 'SQ_PASSWORD',     '***' );
	define( 'SQ_ENGINE',      SourceQuery::SOURCE );
	// Edit this <-
	
	$Query = new SourceQuery( );
	
	try
	{
		$Query->Connect( SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE );

		$Query->SetRconPassword(SQ_PASSWORD);

		print_r( $Query->Rcon('status') );

		print_r( $Query->GetInfo( ) );
	}
	catch( Exception $e )
	{
		echo $e->getMessage( );
	}
		
	$Query->Disconnect( );

$Query->Rcon('status') works well but $Query->GetInfo( ) don't.

Is someone have this ?

**Comment by xPaw** [comment]
Odd. Try to call GetInfo first and then Rcon.

**Comment by EnvoxX** [comment]
Same problem :
GetInfo: Packet header mismatch. (0x6c)

**Comment by xPaw** [comment]
0x6C is response to goldsource rcon, I don't know why you would be getting it on your csgo server.

**Comment by fridary** [comment]
I have the same issue while LGSL from greycube works okey

**Comment by xPaw** [comment]
Are you using `master` version or `1.0.0`? There might be some issue in master.

**Comment by EnvoxX** [comment]
HLSW works well on our servers, so i don't know if there is problems on our config or the lib. It works on some servers, but not all. All have the same config.

**Comment by xPaw** [comment]
Answer my previous question, are you using `master` version or `1.0.0`?
