### ISSUE TITLE
Composer ....

### ISSUE THREAD

**Issue by ImChip** [xPaw/PHP-Source-Query#81]
Hi ,
already sent a issue here https://github.com/xPaw/PHP-Source-Query/issues/68

but i update composer and he not working now ..

my index.php file
```PHP
<?php 
  require 'vendor/autoload.php';
  define( 'SQ_SERVER_ADDR', 'IP' );
  define( 'SQ_SERVER_PORT', 2503 );
  define( 'SQ_TIMEOUT',     1 );
  define( 'SQ_ENGINE',      SourceQuery :: SOURCE );

  $Query = new \SourceQuery( );
  
  try
  {
    $Query->Connect( SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE );
    $player = $Query->GetInfo();
  }
  catch( Exception $e )
  {
    echo $e->getMessage();
  }
  
  $Query->Disconnect();
?>
```
got this error

Fatal error: Class 'SourceQuery' not found in K:\git\homelife\www-homelife\templates\pages\index.php on line 8 

ty

**Comment by xPaw** [comment]
Namespace is `xPaw\SourceQuery`

**Comment by ImChip** [comment]
same error 
with 
  $Query = new \xPaw\SourceQuery\SourceQuery();
