### ISSUE TITLE
composer 

### ISSUE THREAD

**Issue by ImChip** [xPaw/PHP-Source-Query#82]
HI again 
i found a temp solution i require 

  require 'vendor/xpaw/php-source-query-class/SourceQuery/bootstrap.php';

  use xPaw\SourceQuery\SourceQuery;

now 

  $Query = new SourceQuery(); working 

i never mind why this library not working on me with composer

**Comment by xPaw** [comment]
You have to use composer's generated autoloader (or as you did, manually requering my bootstrap.php from vendor folder).
