### ISSUE TITLE
Im so sorry need help

### ISSUE THREAD

**Issue by sixtendk** [xPaw/PHP-Source-Query#84]
I'm so sorry for writing here but i really need help and i'm not so good at this
![sxssasa](https://cloud.githubusercontent.com/assets/16705295/12328952/2069172a-bade-11e5-9e49-72b7024c46ef.PNG)

**Comment by xPaw** [comment]
Please don't create pointless issues for every problem you run into.

**Comment by sixtendk** [comment]
How else to get in contact with u or get some selly help m8
