### ISSUE TITLE
socket errors

### ISSUE THREAD

**Issue by isayldz** [xPaw/PHP-Source-Query#85]
Failed to read any data from socket

#0 /var/www/html/servers/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 /var/www/html/servers/SourceQuery/SourceQuery.php(422): xPaw\SourceQuery\Socket->Read()
#2 /var/www/html/servers/Examples/View.php(28): xPaw\SourceQuery\SourceQuery->GetRules()
#3 {main}

**Comment by Gummibeer** [comment]
:+1: Same problem

**Comment by xPaw** [comment]
Are you using this version? https://github.com/xPaw/PHP-Source-Query/releases/tag/1.0.0

**Comment by Gummibeer** [comment]
In my case it was `dev-master` will update it to `1.0.0` and run the code again

**Comment by Gummibeer** [comment]
Now I'm using the `1.0.0` release but don't get any data, also no exception;
The `Connect()` method returns `null` and the `GetInfo()` & `GetPlayers()` return `false`.

**Comment by isayldz** [comment]
yes i using that veriosn

**Comment by isayldz** [comment]
i install this  but i get this error now  #0 /var/www/html/servers/Examples/View.php(26): xPaw\SourceQuery\SourceQuery->GetInfo()
#1 {main}
