### ISSUE TITLE
Fails once down server is queried

### ISSUE THREAD

**Issue by exi1ed0ne** [xPaw/PHP-Source-Query#87]
Game: Rust
PHP Ver: 5.6.17

I'm working on a test script to cycle through IPs and Ports and do a simple check to see of Rust is running or not.  I've put the query in a function and call it in a simple page below:

```
<?php

require __DIR__ . '/libs/SourceQuery/bootstrap.php';
use xPaw\SourceQuery\SourceQuery;

function GetStatus($IP, $Port) {

	define( 'SQ_SERVER_ADDR', "$IP" );
	define( 'SQ_SERVER_PORT', "$Port" ); 
	define( 'SQ_TIMEOUT',     3 );
	define( 'SQ_ENGINE',      SourceQuery::SOURCE );
	
	$Query = new SourceQuery( );
	$Info    = Array( );

	//wtf - passing the right shit?
	echo "$IP\n";
	echo "$Port\n";	
	
	try {
		$Query->Connect( SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE );
			
		//$Info    = $Query->GetInfo( );
	}
	catch( Exception $e )
	{
		$Exception = $e;
		//wtf - show me the exception
		echo $Exception;
	}
	finally {
		if ($Exception) {
			$result = 'Down';
		} else {
			$result = 'Up';
		}
	}
	
	//wtf - what are we returning
	echo $result;
	$Query->Disconnect( );
	return($result);
}

//Dead Host
$IPMod = '158.69.141.203';
$PortMod = '28035';
$Status = GetStatus($IPMod, $PortMod);
print "<p>Borked is $Status.</p>";

//Live Host
$IPMod = '158.69.141.203';
$PortMod = '28098';
$Status = GetStatus($IPMod, $PortMod);
print "<p>Live is $Status.</p>";

?>
```

Eventually I'll be pulling IP/Port combos from a database, and this is just a test script.  When I run it this is what is output:

> 158.69.141.203 28035 exception 'xPaw\SourceQuery\Exception\InvalidPacketException' with message 'Failed to read any data from socket' in /var/www/vhosts/pessimists.net/httpdocs/rust/libs/SourceQuery/BaseSocket.php:47 Stack trace: #0 /var/www/vhosts/pessimists.net/httpdocs/rust/libs/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array) #1 /var/www/vhosts/pessimists.net/httpdocs/rust/libs/SourceQuery/SourceQuery.php(210): xPaw\SourceQuery\Socket->Read() #2 /var/www/vhosts/pessimists.net/httpdocs/rust/Ping.php(24): xPaw\SourceQuery\SourceQuery->GetInfo() #3 /var/www/vhosts/pessimists.net/httpdocs/rust/Ping.php(47): GetStatus('158.69.141.203', '28035') #4 {main}Down
> 
> Borked is Down.
> 158.69.141.203 28098 exception 'xPaw\SourceQuery\Exception\InvalidPacketException' with message 'Failed to read any data from socket' in /var/www/vhosts/pessimists.net/httpdocs/rust/libs/SourceQuery/BaseSocket.php:47 Stack trace: #0 /var/www/vhosts/pessimists.net/httpdocs/rust/libs/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array) #1 /var/www/vhosts/pessimists.net/httpdocs/rust/libs/SourceQuery/SourceQuery.php(210): xPaw\SourceQuery\Socket->Read() #2 /var/www/vhosts/pessimists.net/httpdocs/rust/Ping.php(24): xPaw\SourceQuery\SourceQuery->GetInfo() #3 /var/www/vhosts/pessimists.net/httpdocs/rust/Ping.php(55): GetStatus('158.69.141.203', '28098') #4 {main}Down
> 
> Live is Down.

When I comment out the borked server check live shows Up as expected, and according to the errors it is getting the right IP/port.  It looks like once it hits a down host it never recovers.  Is there something I'm missing here besides just being blind and stupid?

**Comment by xPaw** [comment]
Try using 1.0.0 release.

**Comment by exi1ed0ne** [comment]
Changed to 1.0.0.  The InvalidPacketException messages are gone, but both statuses are still the same when one host is down.  I also changed the test on $Exception to $Info[Protocol] just in case it was non-null for some reason and flipped the results, but the up host is still showing down.

`finally {
		if ($Info[Protocol]) {
			$result = 'Up';
		} else {
			$result = 'Down';
		}`
I also turned on the first server and turned off the second, and they are both showing Up.  Whatever status the first has it looks like is just copied to the next one, even though the function is getting the right IP and port.

**Comment by xPaw** [comment]
Sounds like UDP quirkiness or something. Nowhere does the library re-use buffers like that, especially since you're re-creating a new instance.

**Comment by exi1ed0ne** [comment]
Yeah, probably some UDP voodoo since both instances are on the same IP.  Even with a sleep(25); between calls it reports the same thing.  I'll try my setup on another box and see if that makes a difference.  Thanks for looking!

**Comment by exi1ed0ne** [comment]
Minor update - it looks to be on the php server end.  Different IP and ports exhibit the same thing.

**Comment by exi1ed0ne** [comment]
It's the define statement - never changes the IP or port when the function is called again.  First one there wins.  Gah.

**Comment by xPaw** [comment]
Well there you go. You don't need to use defines there, just pass the variables directly.
