### ISSUE TITLE
Invalid rcon response.

### ISSUE THREAD

**Issue by iScripters** [xPaw/PHP-Source-Query#89]
When trying to use this with a Rust server, sending any command would always return `Invalid rcon response.`. I commented out line 140 in SourceRcon.php

```
throw new InvalidPacketException( 'Invalid rcon response.', InvalidPacketException::PACKET_HEADER_MISMATCH );
```

And now I get an actual response.

```
string(36) "[RCON][ip.ad.dre.ss:47112] say Hi"
```

I'm sure this is because Rust sent back a wrong/malformed packet, but does it mess up anything else that you can think of if I leave this line commented out?

**Comment by xPaw** [comment]
Dump raw bytes please.

**Comment by iScripters** [comment]
```
object(xPaw\SourceQuery\Buffer)#5 (3) {
  ["Buffer":"xPaw\SourceQuery\Buffer":private]=>
  string(46) "�������[RCON][ip.ad.dre.ss:53982] status��"
  ["Length":"xPaw\SourceQuery\Buffer":private]=>
  int(46)
  ["Position":"xPaw\SourceQuery\Buffer":private]=>
  int(0)
}
```

**Comment by xPaw** [comment]
Post in hex please, these question marks don't help.

**Comment by iScripters** [comment]
How would I do that? Simply bin2hex($Buffer) gives NULL (which can be expected)

**Comment by xPaw** [comment]
Eh, just replace lines 130-132 with this:

```
			var_dump($Buffer->GetLong( )); // RequestID
			
			$Type = $Buffer->GetLong( );
			var_dump($Type);
```

Ideally first value should be `2` (second command after auth) and second `0`

**Comment by iScripters** [comment]
int(1329812059)
int(828071246)

**Comment by xPaw** [comment]
That's not normal. Either way, RCON support in Rust was always buggy, I can't help you further than that.

**Comment by iScripters** [comment]
I'm ok with how it works now, commenting out the exception. Just wondered if it would/could break something else in your class

**Comment by iScripters** [comment]
@xPaw 
I made a packet capture of the commands 'status' and 'players'. Would you be interested in the pcap to analyze? I filtered out everything else, so it's just 16 packets.
