### ISSUE TITLE
send two commands Rcon

### ISSUE THREAD

**Issue by nos30** [xPaw/PHP-Source-Query#91]
Hello!

Is it possible to send two commands Rcon a result?

for example

try {
$ Query-> Connect (SQ_SERVER_ADDR, SQ_SERVER_PORT, SQ_TIMEOUT, SQ_ENGINE);
$ Query-> SetRconPassword ($ rconpassword);
var_dump ($ Query-> Rcon ( 'eco.c deposit' $ steamid '100000')..);
var_dump ($ Query-> Rcon ( 'eco.c deposit' $ steamid '500').);
}

thanks!

**Comment by chasgames** [comment]
Took me a while, i didn't understand why this was closed without explanation.

@nos30  see https://github.com/xPaw/PHP-Source-Query/issues/96
