### ISSUE TITLE
GetRules() not working on CS:GO

### ISSUE THREAD

**Issue by excalibur3000** [xPaw/PHP-Source-Query#92]
Hello,

first of all this is a really nice plugin. Hope this will be enhanced further on. Although the GetRules() funktion isn't working for me. In neither example this brings up any information.

`Failed to read any data from socket`

On the View.php it brings up following error:

`xPaw\SourceQuery\Exception\InvalidPacketException at line 47
Failed to read any data from socket

#0 /var/www/html/test/SourceQuery/Socket.php(76): xPaw\SourceQuery\BaseSocket->ReadInternal(Object(xPaw\SourceQuery\Buffer), 1400, Array)
#1 /var/www/html/test/SourceQuery/SourceQuery.php(422): xPaw\SourceQuery\Socket->Read()
#2 /var/www/html/test/Examples/View.php(28): xPaw\SourceQuery\SourceQuery->GetRules()
#3 {main`

My fault? Every other function is working well.

Best regards Chistian

**Comment by xPaw** [comment]
Blame CS:GO devs, they broke it. You have mess around with some cvars/config files to make it work again.
