### ISSUE TITLE
In the old version, I can use `RCON` properly.

### ISSUE THREAD

**Issue by lurrpis** [xPaw/PHP-Source-Query#95]
In the old version, I can use `RCON` properly.

Game `Counter-Strike1.6`

`old version url`
https://github.com/kruvas/PHP-Source-Query-Class/blob/master/SourceQuery.class.php

But in the new version will be reported errors
`Can't connect to RCON server`

Thanks， Please forgive my English is not good

**Comment by xPaw** [comment]
Did you use `SourceQuery::GOLDSOURCE`?

**Comment by lurrpis** [comment]
When i use `SourceQuery::GOLDSOURCE` display error `Failed to read any data from socket`

Thanks very much

**Comment by xPaw** [comment]
Are you using `1.0.0` release version or `master` zip?

**Comment by lurrpis** [comment]
Haha 
When i using `1.0.0` release version and `SourceQuery::GOLDSOURCE`
The problem is solved

Thank you very much for your trouble.

**Comment by xPaw** [comment]
Looks like there is a bug in master then, I'll leave this open.

**Comment by xPaw** [comment]
I've fixed the issue, can you try `master` and see if it works for you too?
