### ISSUE TITLE
Sending multiple RCON commands in Rust

### ISSUE THREAD

**Issue by chasgames** [xPaw/PHP-Source-Query#96]
Delete these lines in SourceQuery/SourceRcon.php

```
            else if( $Type !== SourceQuery::SERVERDATA_RESPONSE_VALUE )
            {
                throw new InvalidPacketException( 'Invalid rcon response.', InvalidPacketException::PACKET_HEADER_MISMATCH );
            }
```

Wolla! Works now.

Also if your sending time consuming commands like server.save, you need to sleep(10); after for following RCON commands to work.

**Comment by xPaw** [comment]
Just because Rust doesn't implement RCON correctly doesn't mean it's a problem with the library. The server is supposed to be sending SERVERDATA_RESPONSE_VALUE.

Either way, isn't Rust moving towards a different RCON implementation?
