### ISSUE TITLE
multiple querry is not supportet

### ISSUE THREAD

**Issue by paeaet** [xPaw/PHP-Source-Query#97]
I created a automated querry, querriing a server each 5 minutes and write the result in a database, but after the first querry, the script is not working.

maybe there is a fix or sth.

with your minecrat query calss there is no problem

**Comment by Gummibeer** [comment]
Same question as nearly everytime:
* What exactly means `but after the first querry, the script is not working.` (Exception, StackTrace ...)
* What have you done to fix/debug it?
* Can you show your code that creates the error?
* ...

**Comment by xPaw** [comment]
Do you have same problem as this? https://github.com/xPaw/PHP-Source-Query/issues/87#issuecomment-180510251

Anyway, this isn't a problem with the library.
