### ISSUE TITLE
Server query returning false values

### ISSUE THREAD

**Issue by huntert98** [xPaw/PHP-Source-Query#98]
Not quite sure how to explain this, but quite often on my ARK Survival Evolved server the query returns a null player name and an online time for that player. It seems like its a bug caused by a player connecting or disconnecting that says that a player is online, but because there isn't it doesn't have a name to display. I can fix it by restarting the ARK server so I'm not sure if its the query or the server. Either way you can see an example on right side-bar on my website: chaostheorygaming.org

**Comment by xPaw** [comment]
That's a problem with ARK, not this library.
